Update views.py
The ResourceNotFound exception is no longer located in couchdb.client but directly from couchdb.

>>> from couchdb.client import ResourceNotFound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ResourceNotFound
>>> from couchdb import ResourceNotFound
>>> 

I still can't get the tutorial to work on 127.0.0.1:8000 though.